local:
  hosts:
    192.168.1.80:
      domain: nourit.dev
      root_path: "/home/{{ ansible_user }}/nourit.dev"
      self_signed: yes
      database: nourit
      database_password: dotted-statue-hurt
      typesense_key: P8SSmEw4gvSe3gdQXyyQW87FYr4AKRf5Sxk5nrXGyGk
      ansible_user: root
# remote:
#   hosts:
#     nourit:
#       ansible_user: root
#       domain: nourit.fr
#       root_path: "/home/{{ ansible_user }}/nourit.fr"
#       plausible_path: "/home/{{ ansible_user }}/stats.nourit.fr"
#       self_signed: no
#       database: nourit
#       ansible_python_interpreter: /usr/bin/python3
#       docker: false
#       php_version: 8.2
