---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/
- name: Import de la base de données
  hosts: remote
  become: yes

  tasks:
    - name: PostgreSQL | Copie du dump
      copy:
        force: yes
        src: ../../var/dump.tar
        dest: "{{ root_path }}/var/dump.tar"
    - name: PostgreSQL | Reinitialisation de la base de donnée
      become: yes
      become_user: postgres
      community.general.postgresql_db:
        name: "{{ database }}"
        encoding: 'UTF-8'
        lc_collate: 'fr_FR.UTF-8'
        lc_ctype: 'fr_FR.UTF-8'
        template: template0
        state: "{{ item }}"
      with_items:
        - absent
        - present
    - name: PostgreSQL | Import des données
      become: yes
      become_user: postgres
      community.general.postgresql_db:
        state: restore
        target: "{{ root_path }}/var/dump.tar"
        name: "{{ database }}"
