---
- name: GoAccess | GPG Key
  apt_key:
    url: https://deb.goaccess.io/gnugpg.key
- name: GoAccess | repository
  apt_repository:
    repo: deb https://deb.goaccess.io/ {{ ansible_distribution_release }} main
    state: present
- name: GoAccess | Install
  apt:
    name:
      - goaccess
      - libncursesw5-dev
      - libgeoip-dev
      - libmaxminddb-dev
      - libssl-dev
    state: present
- name: Goaccess | Service
  become: no
  template:
    src: "goaccess.service.j2"
    dest: ~/.config/systemd/user/goaccess.service
- name: GoAccess | Activation du Service
  become: no
  systemd:
    scope: user
    state: started
    daemon_reload: yes
    enabled: yes
    name: "goaccess"
# - name: GoAccess | +x Report script
#   become: no
#   file:
#     dest: "{{ root_path }}/tools/goaccess/report.sh"
#     mode: a+x
# - name: GoAccess | Report cron
#   become: no
#   cron:
#     name: goaccess report
#     special_time: hourly
#     job: "{{ root_path }}/tools/goaccess/report.sh"
