---
- name: Outils | Timezone
  community.general.timezone:
    name: Europe/Paris
- name: Outils | Locale française
  community.general.locale_gen:
    name: fr_FR.UTF-8
    state: present
- name: Outils | Requis
  apt:
    name:
      - gnupg
      - curl
    state: present
- name: Outils | Fish GPG Key
  when: ansible_distribution == 'Debian'
  apt_key:
    url: https://download.opensuse.org/repositories/shells:fish:release:3/Debian_{{ ansible_distribution_major_version }}/Release.key
- name: Outils | Fish repository
  when: ansible_distribution == 'Debian'
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_{{ ansible_distribution_major_version }}/ /
    state: present
- name: Outils | Fish ppa
  when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present
- name: Outils | Install
  apt:
    name:
      # - redis
      - fish
      - vim
      - git
      - ntp
      - rsync
      - fail2ban
      - certbot
      - acl
      - make
      - ffmpeg
      # - btop
    state: present
- name: Outils | création de ~/.vim/autoload
  file: state=directory path=~/.vim/autoload
  become: no
- name: Outils | Téléchargement plug.vim
  become: no
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
- name: Outils | Téléchargement .vimrc
  become: no
  get_url:
    url: https://raw.githubusercontent.com/nourit/dotfiles/master/config/vim/.vimrc
    dest: ~/.vimrc
- name: Outils | Fish config directory
  become: no
  file:
    path: ~/.config/fish
    state: directory
- name: Outils | Fish config
  become: no
  template:
    src: config.fish
    dest: ~/.config/fish/config.fish
- name: Outils | Passage sur fish
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/fish
- name: Outils | Fisherman
  become: no
  shell:
    warn: false
    executable: /usr/bin/fish
    cmd: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher && fisher install rafaelrinaldi/pure
    creates: ~/.config/fisher
- name: Outils | Systemd user directory
  become: no
  file:
    path: ~/.config/systemd/user
    state: directory
