---
- name: NodeJS | GPG Key
  when: ansible_distribution == 'Debian'
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
- name: NodeJS | NodeJS {{ node_version }} Debian repository
  when: ansible_distribution == 'Debian'
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main
    state: present
  with_items:
    - deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main
    - deb-src https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main
- name: NodeJS | NodeJS {{ node_version }} Ubuntu repository
  when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: ppa:chris-lea/node.js
    state: present
- name: NodeJS | Install
  apt:
    update_cache: yes
    name:
      - nodejs
    state: present
